name: Benchmarks

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [CPU, GPU]
    steps:
      - name: Checkout OpenXLA
        uses: actions/checkout@v3
        with:
          repository: 'openxla/xla'
          path: openxla

      - name: Build run_hlo_module
        working-directory: openxla
        run: bazelisk build -c opt --dynamic_mode=off xla/tools:run_hlo_module

      - name: Run HLO Module Benchmarks
        working-directory: openxla
        continue-on-error: true
        run: |
          for file in xla/tests/fuzz/*.hlo; do
            echo "Running benchmark for ${{ matrix.platform }} on $file"
            ./bazel-bin/xla/tools/run_hlo_module --input_format=hlo --platform=${{ matrix.platform }} $file
          done

      - name: Build CPU Benchmarks
        working-directory: openxla
        run: bazelisk build -c opt --dynamic_mode=off //xla/service/cpu/benchmarks:*

      - name: Run CPU benchmarks
        working-directory: openxla
        continue-on-error: true
        run: |
          for benchmark in $(bazelisk query 'kind("executable", //xla/service/cpu/benchmarks:*)'); do
              echo "Running: $benchmark"
              ./bazel-bin/$benchmark --benchmark_filter=".*"
            
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-xla-benchmarks
          path: openxla/xla
