name: Benchmarks

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

      - name: Run benchmarks
        run: echo "running benchmarks" 

      # TODO(juliagmt-google): Add actual benchmark commands here.  
      
