name: Benchmarks

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout OpenXLA
        uses: actions/checkout@v3
        with:
          repository: 'openxla/xla'
          path: openxla

      - name: Create results directory
        working-directory: openxla
        run: mkdir results

      - name: Build CPU Benchmarks
        working-directory: openxla
        run: bazelisk build -c opt --dynamic_mode=off //xla/service/cpu/benchmarks:*

      - name: Run CPU benchmarks
        working-directory: openxla
        continue-on-error: true
        run: |
          find ./bazel-bin/xla/service/cpu/benchmarks/ -maxdepth 1 -type f -executable -name "*_test" -print0 | while IFS= read -r -d $'\0' benchmark; do
            # Extract the benchmark name (remove path and extension)
            benchmark_name=$(basename "$benchmark" | sed 's/_test$//') 

            echo "Running benchmark: $benchmark_name"

            # Run the benchmark with default parameters and save the output to a log file.
            $benchmark --benchmark_filter=".*" > "results/$benchmark_name.log" 2>&1

            # Check the exit code of the benchmark
            if [ $? -ne 0 ]; then
              echo "Error: Benchmark '$benchmark_name' failed. Check the log file: results/$benchmark_name.log"
            else
              echo "Benchmark '$benchmark_name' completed successfully."
            fi
          done

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: cpu-xla-benchmarks
          path: openxla/results
